#!/usr/bin/env python3
# @capability:  capability-registry
# @compute:     deterministic
# @effect:      read-only
# @engine:      scripts/registry-generate.py
# @prompt:      (none)
# @adapters:    cli
# @portability: L1a-generic
# @forbidden:   n/a
# @audit:       none
# @status:      active
# @doc:         docs/pattern-portable-core-and-adapters.md
"""
registry-generate.py -- DETERMINISTIC capability registry generator.

Scans the harness for per-capability metadata headers (the convention in the pattern doc, section 8)
and EMITS the catalog. Anti-rot by construction: the registry is generated from the source-of-truth
headers, never hand-maintained. Capabilities without a header are listed as the classification backlog.

Header fields (in a script's top comment block OR a command's YAML frontmatter; one per line,
matching `@field: value`):
  @capability @compute @effect @engine @prompt @adapters @portability @forbidden @audit @status @doc

Usage: python scripts/registry-generate.py [--json] [--write]
  (default: print markdown to stdout; --write emits docs/capability-registry.md)
"""
import os, re, sys, json


def _detect_root_and_scan():
    """Locate the tree to scan whether running from a repo/plugin checkout (engines in scripts/) or
    from an installed wheel (engines force-included under the package as _engines/ + _prompts/).
    Without this, `neurokeeper registry-generate` would scan an empty tree after a pipx/wheel install."""
    if os.environ.get("HARNESS_ROOT"):
        return os.environ["HARNESS_ROOT"], ["scripts", "skills", "prompts", "hooks", "commands",
                                            "_engines", "_prompts"]
    here = os.path.dirname(os.path.abspath(__file__))   # dir holding this engine
    parent = os.path.dirname(here)
    if os.path.isdir(os.path.join(parent, "scripts")):  # repo / plugin checkout: <root>/scripts/
        return parent, ["scripts", "skills", "prompts", "hooks", "commands"]
    if os.path.basename(here) == "_engines":            # installed wheel: <package>/_engines/ + _prompts/
        return parent, ["_engines", "_prompts"]
    return here, ["."]                                   # fallback: this engine's own dir


ROOT, SCAN = _detect_root_and_scan()
EXT = (".py", ".js", ".sh", ".md")
FIELDS = ["capability","compute","effect","engine","prompt","adapters",
          "portability","forbidden","audit","status","doc"]
FIELD_RE = re.compile(r"@(" + "|".join(FIELDS) + r")\s*:\s*(.+?)\s*$")

def parse(path):
    """Extract @fields from the first 40 lines (comment header or YAML frontmatter)."""
    found = {}
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            for i, line in enumerate(f):
                if i >= 40: break
                m = FIELD_RE.search(line)
                if m: found[m.group(1)] = m.group(2).strip()
    except Exception:
        pass
    return found

def main():
    for _s in (sys.stdout, sys.stderr):            # cross-platform UTF-8 (Windows defaults cp1252)
        try: _s.reconfigure(encoding="utf-8")
        except Exception: pass
    as_json = "--json" in sys.argv
    write = "--write" in sys.argv
    classified, backlog = [], []
    for d in SCAN:
        base = os.path.join(ROOT, d)
        if not os.path.isdir(base): continue
        for root, dirs, files in os.walk(base):
            for fn in files:
                if not fn.endswith(EXT): continue
                rel = os.path.relpath(os.path.join(root, fn), ROOT).replace("\\", "/")
                hdr = parse(os.path.join(root, fn))
                if "capability" in hdr:
                    hdr["_file"] = rel
                    classified.append(hdr)
                else:
                    backlog.append(rel)
    classified.sort(key=lambda h: (h.get("portability","zzz"), h.get("capability","")))

    if as_json:
        print(json.dumps({"classified": classified, "backlog": backlog,
                          "counts": {"classified": len(classified), "backlog": len(backlog)}},
                         indent=2, ensure_ascii=False)); return

    out = []
    out.append("# Capability registry (GENERATED -- do not hand-edit)")
    out.append("")
    out.append("Generated by `scripts/registry-generate.py` from per-capability `@`-headers.")
    out.append(f"Classified: **{len(classified)}** · Unclassified backlog: **{len(backlog)}**. "
               "Add a header (pattern doc section 8) to classify a backlog item; re-run to regenerate.")
    out.append("")
    out.append("| capability | compute | effect | portability | forbidden | audit | status | engine | adapters |")
    out.append("|---|---|---|---|---|---|---|---|---|")
    for h in classified:
        out.append("| {capability} | {compute} | {effect} | {portability} | {forbidden} | {audit} | "
                   "{status} | `{engine}` | {adapters} |".format(
            capability=h.get("capability","?"), compute=h.get("compute","?"),
            effect=h.get("effect","?"), portability=h.get("portability","?"),
            forbidden=h.get("forbidden","?"), audit=h.get("audit","?"),
            status=h.get("status","?"), engine=h.get("engine", h.get("_file","?")),
            adapters=h.get("adapters","?")))
    out.append("")
    out.append("## Unclassified backlog (add an @capability header to register)")
    out.append("")
    if backlog:
        for f in sorted(backlog): out.append(f"- `{f}`")
    else:
        out.append("(none -- all scanned assets classified)")
    out.append("")
    out.append("## Not scanned per-file (bundled capabilities)")
    out.append("- a private document-render engine bundle (L1b private-mechanism; "
               "domain-specific). Register as one bundled capability rather than per-file.")
    md = "\n".join(out) + "\n"

    if write:
        dst = os.path.join(ROOT, "docs", "capability-registry.md")
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        open(dst, "w", encoding="utf-8", newline="").write(md)
        print(f"wrote {dst} ({len(classified)} classified, {len(backlog)} backlog)")
    else:
        print(md)

if __name__ == "__main__":
    main()
